name: website_for_kuya
description: A new Flutter project.

publish_to: 'none' # Remove this line if you plan to publish

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"
  # Added google_fonts for typography samples

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.0.0
  http: ^1.1.0
  flutter_staggered_grid_view: ^0.6.2
  rive: ^0.12.4
  lottie: ^2.6.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
